// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func TabButtons() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"mb-4 flex flex-wrap gap-2\" role=\"tablist\" aria-label=\"Workflow tabs\"><button type=\"button\" @click=\"activeTab = 'configuration'\" :class=\"activeTab === 'configuration'\n      ? 'rounded-2xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white transition'\n      : 'rounded-2xl bg-slate-100 px-4 py-2 text-sm font-semibold text-slate-600 transition hover:bg-slate-200'\" :aria-selected=\"activeTab === 'configuration'\">Configuration</button> <button type=\"button\" @click=\"activeTab = 'file-transfer'\" :class=\"activeTab === 'file-transfer'\n      ? 'rounded-2xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white transition'\n      : 'rounded-2xl bg-slate-100 px-4 py-2 text-sm font-semibold text-slate-600 transition hover:bg-slate-200'\" :aria-selected=\"activeTab === 'file-transfer'\">File Transfer</button> <button type=\"button\" @click=\"activeTab = 'checking'\" :class=\"activeTab === 'checking'\n      ? 'rounded-2xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white transition'\n      : 'rounded-2xl bg-slate-100 px-4 py-2 text-sm font-semibold text-slate-600 transition hover:bg-slate-200'\" :aria-selected=\"activeTab === 'checking'\">Checking</button></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
